apiVersion: v1 
kind: PersistentVolume
metadata:
  name: ebs-static
spec: 
  accessModes: 
  - ReadWriteOnce    # At a time only one user can Read Write Once.
  capacity: 
    storage: 20Gi
  csi:  #Container Storage Interface. 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0018dc911c2510822
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts: #docker run -v hostpath:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static-demo
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: 80 #container port