apiVersion: v1 
kind: PersistentVolume
metadata:
  name: ebs-static
spec: 
  accessModes: 
  - ReadWriteOnce    # At a time only one user can Read Write Once.
  capacity: 
    storage: 20Gi
  csi:  #Container Storage Interface. 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0018dc911c2510822
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi