apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:   
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: " " # This should be empty in static provisioning 
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0dc93f7f13e6e6029