apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # deployment labels
  labels:
    purpose: Deployment-demo 
    project: roboshop 
    app: nginx
spec:
  replicas: 3
# These are the labels replica set use to create pod replicas, This should match pod labels.
  selector:
    matchLabels:
      purpose: Deployment-demo
      project: roboshop 
      app: nginx
  template:
  # This pod defination
    metadata:
      labels:
        purpose: Deployment-demo
        project: roboshop 
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:
    purpose: service-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: 80 #container port